# Generated by Django 4.2 on 2023-07-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='childModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('integer', models.IntegerField()),
                ('small_text', models.CharField(max_length=100)),
                ('large_text', models.TextField()),
                ('date', models.DateField()),
                ('repair_state', models.CharField(choices=[('B', '수리전'), ('A', '수리후')], default='B', max_length=1)),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space1.parentmodel')),
            ],
        ),
    ]
